### ISSUE TITLE
집 기능 추가

### ISSUE THREAD

**Issue by Forgot09** [kty0205/TextRPG#3]
집 메뉴로 들어갔을 때 ['정보 보기', '저장', '저장 및 나가기']가 있던데 저장 및 나가기를 저장 하고 집을 나가서 마을로 돌아가는 걸로 하면 안되나요? 집으로 들어가면 마을로 나오는 방법이 없어요. 기능 통폐합 및 수정 부탁드립니다.

**Comment by kty0205** [comment]
어딘가에서 나가거나 뒤로가는 방법은 아무것도 입력하지 않은상태에서 Enter를 누르면 됩니다. 이걸 안적어놨군요.
